# Chapter 2 Problems - Python

## Load Libraries

In [15]:
#### Install the libraries - Only needs to be done once
# !pip3 install numpy
# !pip3 install pandas
# !pip3 install statsmodels
# !pip3 install xlrd

## 2.1

In [21]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import xlrd
import os

In [23]:
wb = xlrd.open_workbook('../linear_regression_5e_data_sets/Appendices/data-table-B1.XLS', logfile=open(os.devnull, 'w'))
df = pd.read_excel(wb, engine='xlrd')

In [26]:
df = df[['y','x8']]
df = df.rename(columns={'x8':'x'})
y = df['y'].to_numpy()
x = df['x'].to_numpy()

In [32]:
x = sm.add_constant(x)

In [58]:
model = sm.OLS(y, x)
results = model.fit()

In [60]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.545
Model:                            OLS   Adj. R-squared:                  0.527
Method:                 Least Squares   F-statistic:                     31.10
Date:                Sat, 24 Jul 2021   Prob (F-statistic):           7.38e-06
Time:                        11:29:36   Log-Likelihood:                -63.123
No. Observations:                  28   AIC:                             130.2
Df Residuals:                      26   BIC:                             132.9
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         21.7883      2.696      8.081      0.0

In [37]:
dir(results)

['HC0_se',
 'HC1_se',
 'HC2_se',
 'HC3_se',
 '_HCCM',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abat_diagonal',
 '_cache',
 '_data_attr',
 '_data_in_cache',
 '_get_robustcov_results',
 '_is_nested',
 '_use_t',
 '_wexog_singular_values',
 'aic',
 'bic',
 'bse',
 'centered_tss',
 'compare_f_test',
 'compare_lm_test',
 'compare_lr_test',
 'condition_number',
 'conf_int',
 'conf_int_el',
 'cov_HC0',
 'cov_HC1',
 'cov_HC2',
 'cov_HC3',
 'cov_kwds',
 'cov_params',
 'cov_type',
 'df_model',
 'df_resid',
 'diagn',
 'eigenvals',
 'el_test',
 'ess',
 'f_pvalue',
 'f_test',
 'fittedvalues',
 'fvalue',
 'get_influence',
 'get_prediction',
 'get_robustcov_results',
 'initia

In [38]:
results.mse_resid

5.725845084730775

In [39]:
results.mse_model

178.09231351128557

In [40]:
results.ssr

148.87197220300015

In [42]:
results.ess

178.09231351128557

In [43]:
# Equation
results.params
# Clean Up Printing...

array([ 2.17882509e+01, -7.02510028e-03])

In [63]:
results.conf_int

<bound method RegressionResults.conf_int of <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x784c8599ff60>>

In [53]:
# Calculate a new value
newx = 2000
predictions = results.get_prediction([1,newx])

In [56]:
# 
predictions.summary_frame(.05)

mean   mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  obs_ci_upper
0  7.73805  0.473015       6.765753       8.710348      2.724248     12.751852

In [72]:
results.conf_int(alpha=0.05)[1]

array([-0.00961435, -0.00443585])

In [75]:
np.max(x)

2876.0

In [81]:
print(np.max(x[:,1]))

2876.0


In [82]:
print(np.min(x[:,1]))

1457.0


In [91]:
min_x = np.min(x[:,1])
max_x = np.max(x[:,1])
interval_x = np.arange(min_x,max_x,(max_x - min_x)/100)

In [93]:
interval_x

array([1457.  , 1471.19, 1485.38, 1499.57, 1513.76, 1527.95, 1542.14,
       1556.33, 1570.52, 1584.71, 1598.9 , 1613.09, 1627.28, 1641.47,
       1655.66, 1669.85, 1684.04, 1698.23, 1712.42, 1726.61, 1740.8 ,
       1754.99, 1769.18, 1783.37, 1797.56, 1811.75, 1825.94, 1840.13,
       1854.32, 1868.51, 1882.7 , 1896.89, 1911.08, 1925.27, 1939.46,
       1953.65, 1967.84, 1982.03, 1996.22, 2010.41, 2024.6 , 2038.79,
       2052.98, 2067.17, 2081.36, 2095.55, 2109.74, 2123.93, 2138.12,
       2152.31, 2166.5 , 2180.69, 2194.88, 2209.07, 2223.26, 2237.45,
       2251.64, 2265.83, 2280.02, 2294.21, 2308.4 , 2322.59, 2336.78,
       2350.97, 2365.16, 2379.35, 2393.54, 2407.73, 2421.92, 2436.11,
       2450.3 , 2464.49, 2478.68, 2492.87, 2507.06, 2521.25, 2535.44,
       2549.63, 2563.82, 2578.01, 2592.2 , 2606.39, 2620.58, 2634.77,
       2648.96, 2663.15, 2677.34, 2691.53, 2705.72, 2719.91, 2734.1 ,
       2748.29, 2762.48, 2776.67, 2790.86, 2805.05, 2819.24, 2833.43,
       2847.62, 2861

In [94]:
interval_x = sm.add_constant(interval_x)

In [96]:
predictions = results.get_prediction(interval_x)

In [99]:
predictions.summary_frame(0.05)

mean   mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  \
0   11.552680  0.938819       9.622910      13.482450      6.269039   
1   11.452994  0.923195       9.555339      13.350648      6.180998   
2   11.353307  0.907654       9.487598      13.219017      6.092726   
3   11.253621  0.892200       9.419677      13.087565      6.004221   
4   11.153935  0.876839       9.351567      12.956303      5.915483   
..        ...       ...            ...            ...           ...   
95   2.082493  0.985248       0.057287       4.107700     -3.236746   
96   1.982807  1.001162      -0.075111       4.040725     -3.348973   
97   1.883121  1.017141      -0.207643       3.973885     -3.461422   
98   1.783435  1.033183      -0.340302       3.907172     -3.574093   
99   1.683749  1.049283      -0.473084       3.840581     -3.686984   

    obs_ci_upper  
0      16.836321  
1      16.724989  
2      16.613889  
3      16.503021  
4      16.392387  
..           ...  
95      7.401733  
96      7.314587  
97      7.227664  
98      7.140963  
99      7.054482  

[100 rows x 6 columns]